{% set name = "geoarrow-types" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/geoarrow_types-{{ version }}.tar.gz
  sha256: 2dcb3db9c80b2079a7a61c3e74aa46904f1c899136735f1cacc015757707e924

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - geoarrow.types
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/geoarrow/geoarrow-python
  summary: Lightweight GeoArrow type specification
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - paleolimbot
